# Generated by Django 4.2.4 on 2023-08-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numero_identificacion',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
