# Generated by Django 4.2.4 on 2023-08-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_numero_identificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='archivo_excel',
            field=models.FileField(blank=True, null=True, upload_to='archivos_excel/'),
        ),
    ]
